package main

import (
	"encoding/json"
	"os"
	"path/filepath"
	"sync"
	"testing"
	"time"

	"github.com/nlink-jp/shell-agent/internal/analysis"
)

func TestJobMonitor_TrackAndGetJobs(t *testing.T) {
	m := newJobMonitor()

	dir := t.TempDir()
	outputDir := filepath.Join(dir, "job-1234")
	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		t.Fatal(err)
	}

	// Write initial status
	writeTestStatus(t, outputDir, "running", "initializing")

	// Track without Wails context (events won't emit, but logic works)
	m.mu.Lock()
	m.jobs["job-1234"] = &monitoredJob{
		JobID:     "job-1234",
		Prompt:    "test analysis",
		StartedAt: time.Now(),
		State:     "running",
		Progress:  "initializing",
	}
	m.mu.Unlock()

	jobs := m.GetJobs()
	if len(jobs) != 1 {
		t.Fatalf("expected 1 job, got %d", len(jobs))
	}
	if jobs[0].JobID != "job-1234" {
		t.Errorf("job ID: got %q, want %q", jobs[0].JobID, "job-1234")
	}
	if jobs[0].State != "running" {
		t.Errorf("state: got %q, want %q", jobs[0].State, "running")
	}
	if jobs[0].Prompt != "test analysis" {
		t.Errorf("prompt: got %q, want %q", jobs[0].Prompt, "test analysis")
	}
}

func TestJobMonitor_AcceptAndDefer(t *testing.T) {
	m := newJobMonitor()
	m.mu.Lock()
	m.jobs["job-1"] = &monitoredJob{JobID: "job-1", State: "done"}
	m.mu.Unlock()

	// Accept
	m.AcceptJobResult("job-1")

	m.mu.Lock()
	if !m.jobs["job-1"].Reviewed {
		t.Error("job should be marked as reviewed after Accept")
	}
	m.mu.Unlock()

	// Read channel
	select {
	case resp := <-m.resultCh:
		if !resp.accepted || resp.jobID != "job-1" {
			t.Errorf("unexpected response: %+v", resp)
		}
	default:
		t.Error("expected response in channel")
	}
}

func TestJobMonitor_DeferResult(t *testing.T) {
	m := newJobMonitor()
	m.mu.Lock()
	m.jobs["job-2"] = &monitoredJob{JobID: "job-2", State: "done"}
	m.mu.Unlock()

	m.DeferJobResult("job-2")

	select {
	case resp := <-m.resultCh:
		if resp.accepted || resp.jobID != "job-2" {
			t.Errorf("unexpected response: %+v", resp)
		}
	default:
		t.Error("expected response in channel")
	}

	// Should NOT be marked as reviewed
	m.mu.Lock()
	if m.jobs["job-2"].Reviewed {
		t.Error("deferred job should not be marked as reviewed")
	}
	m.mu.Unlock()
}

func TestJobMonitor_RemoveJob(t *testing.T) {
	m := newJobMonitor()
	m.mu.Lock()
	m.jobs["job-x"] = &monitoredJob{JobID: "job-x"}
	m.mu.Unlock()

	m.RemoveJob("job-x")

	jobs := m.GetJobs()
	if len(jobs) != 0 {
		t.Errorf("expected 0 jobs after remove, got %d", len(jobs))
	}
}

func TestJobMonitor_GetJobs_Empty(t *testing.T) {
	m := newJobMonitor()
	jobs := m.GetJobs()
	if len(jobs) != 0 {
		t.Errorf("expected 0 jobs, got %d", len(jobs))
	}
}

func TestJobMonitor_ConcurrentAccess(t *testing.T) {
	m := newJobMonitor()

	var wg sync.WaitGroup
	for i := 0; i < 20; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			_ = m.GetJobs()
		}()
	}
	for i := 0; i < 10; i++ {
		wg.Add(1)
		go func(id int) {
			defer wg.Done()
			m.mu.Lock()
			m.jobs["job-concurrent"] = &monitoredJob{
				JobID: "job-concurrent",
				State: "running",
			}
			m.mu.Unlock()
		}(i)
	}
	wg.Wait()
}

func TestIsValidAnalysisJobID_Additional(t *testing.T) {
	// Ensure the validation works for job IDs generated by analyzeBgTool
	// Format: job-{unixMilli}
	id := "job-1713488400000"
	if !isValidAnalysisJobID(id) {
		t.Errorf("valid job ID rejected: %s", id)
	}
}

func writeTestStatus(t *testing.T, dir, state, progress string) {
	t.Helper()
	status := analysis.JobStatus{
		State:     state,
		Progress:  progress,
		StartedAt: time.Now(),
		UpdatedAt: time.Now(),
	}
	data, _ := json.MarshalIndent(status, "", "  ")
	if err := os.WriteFile(filepath.Join(dir, "status.json"), data, 0o644); err != nil {
		t.Fatal(err)
	}
}
