// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApproveMITL() {
  return window['go']['main']['App']['ApproveMITL']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetLLMStatus() {
  return window['go']['main']['App']['GetLLMStatus']();
}

export function GetPinnedMemories() {
  return window['go']['main']['App']['GetPinnedMemories']();
}

export function GetTools() {
  return window['go']['main']['App']['GetTools']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function LoadSession(arg1) {
  return window['go']['main']['App']['LoadSession'](arg1);
}

export function NewSession() {
  return window['go']['main']['App']['NewSession']();
}

export function RefreshTools() {
  return window['go']['main']['App']['RefreshTools']();
}

export function RejectMITL() {
  return window['go']['main']['App']['RejectMITL']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}
