// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApproveTool(arg1:string,arg2:string):Promise<string>;

export function GetLLMStatus():Promise<main.LLMStatus>;

export function GetTools():Promise<Array<main.ToolInfo>>;

export function ListSessions():Promise<Array<main.SessionInfo>>;

export function LoadSession(arg1:string):Promise<Array<main.ChatMessage>>;

export function NewSession():Promise<string>;

export function RejectTool(arg1:string):Promise<string>;

export function SendMessage(arg1:string):Promise<main.ChatMessage>;
