// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApproveTool(arg1, arg2) {
  return window['go']['main']['App']['ApproveTool'](arg1, arg2);
}

export function GetLLMStatus() {
  return window['go']['main']['App']['GetLLMStatus']();
}

export function GetTools() {
  return window['go']['main']['App']['GetTools']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function LoadSession(arg1) {
  return window['go']['main']['App']['LoadSession'](arg1);
}

export function NewSession() {
  return window['go']['main']['App']['NewSession']();
}

export function RejectTool(arg1) {
  return window['go']['main']['App']['RejectTool'](arg1);
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}
