// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {main} from '../models';
import {memory} from '../models';

export function ApproveMITL():Promise<void>;

export function DeleteSession(arg1:string):Promise<void>;

export function GetConfig():Promise<config.Config>;

export function GetImageDataURL(arg1:string,arg2:string):Promise<string>;

export function GetLLMStatus():Promise<main.LLMStatus>;

export function GetPinnedMemories():Promise<Array<memory.PinnedMemory>>;

export function GetTools():Promise<Array<main.ToolInfo>>;

export function ListSessions():Promise<Array<main.SessionInfo>>;

export function LoadSession(arg1:string):Promise<Array<main.ChatMessage>>;

export function NewSession():Promise<string>;

export function RefreshTools():Promise<Array<main.ToolInfo>>;

export function RejectMITL():Promise<void>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;

export function SaveConfig(arg1:string):Promise<void>;

export function SendMessage(arg1:string):Promise<main.ChatMessage>;

export function SendMessageWithImages(arg1:string,arg2:Array<string>):Promise<main.ChatMessage>;
