// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApproveMITL() {
  return window['go']['main']['App']['ApproveMITL']();
}

export function CancelExecution() {
  return window['go']['main']['App']['CancelExecution']();
}

export function CopyImageToClipboard(arg1) {
  return window['go']['main']['App']['CopyImageToClipboard'](arg1);
}

export function DeletePinnedMemory(arg1) {
  return window['go']['main']['App']['DeletePinnedMemory'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function GetBlobDataURL(arg1) {
  return window['go']['main']['App']['GetBlobDataURL'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetImageDataURL(arg1, arg2) {
  return window['go']['main']['App']['GetImageDataURL'](arg1, arg2);
}

export function GetLLMStatus() {
  return window['go']['main']['App']['GetLLMStatus']();
}

export function GetPinnedMemories() {
  return window['go']['main']['App']['GetPinnedMemories']();
}

export function GetTools() {
  return window['go']['main']['App']['GetTools']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function LoadSession(arg1) {
  return window['go']['main']['App']['LoadSession'](arg1);
}

export function NewSession() {
  return window['go']['main']['App']['NewSession']();
}

export function RefreshTools() {
  return window['go']['main']['App']['RefreshTools']();
}

export function RejectMITL() {
  return window['go']['main']['App']['RejectMITL']();
}

export function RenameSession(arg1, arg2) {
  return window['go']['main']['App']['RenameSession'](arg1, arg2);
}

export function RestartGuardians() {
  return window['go']['main']['App']['RestartGuardians']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveImageToFile(arg1) {
  return window['go']['main']['App']['SaveImageToFile'](arg1);
}

export function SaveReport(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveReport'](arg1, arg2, arg3);
}

export function SaveSidebarState(arg1, arg2) {
  return window['go']['main']['App']['SaveSidebarState'](arg1, arg2);
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SendMessageWithImages(arg1, arg2) {
  return window['go']['main']['App']['SendMessageWithImages'](arg1, arg2);
}

export function ToggleTool(arg1, arg2) {
  return window['go']['main']['App']['ToggleTool'](arg1, arg2);
}

export function UpdateLocation(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateLocation'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdatePinnedMemory(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdatePinnedMemory'](arg1, arg2, arg3, arg4);
}
