// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {main} from '../models';
import {memory} from '../models';

export function ApproveMITL():Promise<void>;

export function CancelExecution():Promise<void>;

export function CopyImageToClipboard(arg1:string):Promise<void>;

export function DeletePinnedMemory(arg1:number):Promise<boolean>;

export function DeleteSession(arg1:string):Promise<void>;

export function GetBlobDataURL(arg1:string):Promise<string>;

export function GetConfig():Promise<config.Config>;

export function GetImageDataURL(arg1:string,arg2:string):Promise<string>;

export function GetLLMStatus():Promise<main.LLMStatus>;

export function GetPinnedMemories():Promise<Array<memory.PinnedMemory>>;

export function GetTools():Promise<Array<main.ToolInfo>>;

export function GetVersion():Promise<string>;

export function ListSessions():Promise<Array<main.SessionInfo>>;

export function LoadSession(arg1:string):Promise<Array<main.ChatMessage>>;

export function NewSession():Promise<string>;

export function RefreshTools():Promise<Array<main.ToolInfo>>;

export function RejectMITL():Promise<void>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;

export function RestartGuardians():Promise<number>;

export function SaveConfig(arg1:string):Promise<void>;

export function SaveImageToFile(arg1:string):Promise<void>;

export function SaveReport(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function SaveSidebarState(arg1:number,arg2:boolean):Promise<void>;

export function SendMessage(arg1:string):Promise<main.ChatMessage>;

export function SendMessageWithImages(arg1:string,arg2:Array<string>):Promise<main.ChatMessage>;

export function ToggleTool(arg1:string,arg2:boolean):Promise<void>;

export function UpdateLocation(arg1:number,arg2:number,arg3:string,arg4:string,arg5:string):Promise<void>;

export function UpdatePinnedMemory(arg1:number,arg2:string,arg3:string,arg4:string):Promise<boolean>;
